//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hive.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hive.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CdTe {
            get {
                object obj = ResourceManager.GetObject("CdTe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIGS {
            get {
                object obj = ResourceManager.GetObject("CIGS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC tech,electric efficiency,thermal efficiency,cost per m2,life cycle GHG factor kgCO2eq per m2
        ///GC_cheap,0.0,0.1,300.0,1.0
        ///GC_normal,0.0,0.2,400.0,2.0
        ///GC_high_tech,0.0,0.3,500.0,3.0.
        /// </summary>
        internal static string gc_efficiency {
            get {
                return ResourceManager.GetString("gc_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HIT {
            get {
                object obj = ResourceManager.GetObject("HIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monocristalline {
            get {
                object obj = ResourceManager.GetObject("monocristalline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polycristalline {
            get {
                object obj = ResourceManager.GetObject("polycristalline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV tech,electric efficiency,thermal efficiency,cost per m2,life cycle GHG factor kgCO2eq per m2
        ///polycristalline,0.160,0,400.0.0,35.96
        ///polycristalline_high,0.206,0.0,400.0,35.96
        ///monocristalline,0.184,0.0,400.0,35.96
        ///monocristalline_high,0.228,0.0,400.0,35.96
        ///CIGS,0.133,0.0,400.0,35.96
        ///CIGS_high,0.156,0.0,400.0,35.96
        ///CdTe,0.162,0.0,400.0,35.96
        ///CdTe_high,0.182,0.0,400.0,35.96
        ///HIT,0.194,0.0,400.0,35.96
        ///HIT_high,0.209,0.0,400.0,35.96.
        /// </summary>
        internal static string pv_efficiency {
            get {
                return ResourceManager.GetString("pv_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVT tech,electric efficiency,thermal efficiency,cost per m2,life cycle GHG factor kgCO2eq per m2
        ///PVT_cheap,0.1,0.1,300.0,1.0
        ///PVT_normal,0.2,0.2,400.0,2.0
        ///PVT_high_tech,0.3,0.3,500.0,3.0.
        /// </summary>
        internal static string pvt_efficiency {
            get {
                return ResourceManager.GetString("pvt_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST tech,electric efficiency,thermal efficiency,cost per m2,life cycle GHG factor kgCO2eq per m2
        ///solar_thermal_cheap,0.0,0.1,300.0,1.0
        ///solar_thermal_normal,0.0,0.2,400.0,2.0
        ///solar_thermal_high_tech,0.0,0.3,500.0,3.0.
        /// </summary>
        internal static string st_efficiency {
            get {
                return ResourceManager.GetString("st_efficiency", resourceCulture);
            }
        }
    }
}
