//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hive.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hive.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_1_Wohnen_Mehrfamilienhaus {
            get {
                object obj = ResourceManager.GetObject("1.1 Wohnen Mehrfamilienhaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_2_Wohnen_Einfamilienhaus {
            get {
                object obj = ResourceManager.GetObject("1.2 Wohnen Einfamilienhaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10_1_Lagerhalle {
            get {
                object obj = ResourceManager.GetObject("10.1 Lagerhalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_1_Turnhalle {
            get {
                object obj = ResourceManager.GetObject("11.1 Turnhalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_2_Fitnessraum {
            get {
                object obj = ResourceManager.GetObject("11.2 Fitnessraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_3_Schwimmhalle {
            get {
                object obj = ResourceManager.GetObject("11.3 Schwimmhalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_1_Verkehrsflaeche {
            get {
                object obj = ResourceManager.GetObject("12.1 Verkehrsflaeche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_11_Kuehlraum {
            get {
                object obj = ResourceManager.GetObject("12.11 Kuehlraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_12_Serverraum {
            get {
                object obj = ResourceManager.GetObject("12.12 Serverraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_2_Verkehrsflaeche_24_h {
            get {
                object obj = ResourceManager.GetObject("12.2 Verkehrsflaeche 24 h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_3_Treppenhaus {
            get {
                object obj = ResourceManager.GetObject("12.3 Treppenhaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_4_Nebenraum {
            get {
                object obj = ResourceManager.GetObject("12.4 Nebenraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_5_Kueche__Teekueche {
            get {
                object obj = ResourceManager.GetObject("12.5 Kueche, Teekueche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_6_WC__Bad__Dusche {
            get {
                object obj = ResourceManager.GetObject("12.6 WC, Bad, Dusche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_7_WC {
            get {
                object obj = ResourceManager.GetObject("12.7 WC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12_8_Garderobe__Dusche {
            get {
                object obj = ResourceManager.GetObject("12.8 Garderobe, Dusche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_1_Hotelzimmer {
            get {
                object obj = ResourceManager.GetObject("2.1 Hotelzimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_2_Empfang__Lobby {
            get {
                object obj = ResourceManager.GetObject("2.2 Empfang, Lobby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_1_Einzel___Gruppenbuero {
            get {
                object obj = ResourceManager.GetObject("3.1 Einzel-, Gruppenbuero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_2_Grossraumbuero {
            get {
                object obj = ResourceManager.GetObject("3.2 Grossraumbuero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_3_Sitzungszimmer {
            get {
                object obj = ResourceManager.GetObject("3.3 Sitzungszimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_4_Schalterhalle__Empfang {
            get {
                object obj = ResourceManager.GetObject("3.4 Schalterhalle, Empfang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_1_Schulzimmer {
            get {
                object obj = ResourceManager.GetObject("4.1 Schulzimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_2_Lehrerzimmer {
            get {
                object obj = ResourceManager.GetObject("4.2 Lehrerzimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_3_Bibliothek {
            get {
                object obj = ResourceManager.GetObject("4.3 Bibliothek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_4_Hoehrsaal {
            get {
                object obj = ResourceManager.GetObject("4.4 Hoehrsaal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_5_Schulfachraum {
            get {
                object obj = ResourceManager.GetObject("4.5 Schulfachraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_1_Lebensmittelverkauf {
            get {
                object obj = ResourceManager.GetObject("5.1 Lebensmittelverkauf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_2_Fachgeschaeft {
            get {
                object obj = ResourceManager.GetObject("5.2 Fachgeschaeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_3_Verkauf_Moebel__Bau__Garten {
            get {
                object obj = ResourceManager.GetObject("5.3 Verkauf Moebel, Bau, Garten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_1_Restaurant {
            get {
                object obj = ResourceManager.GetObject("6.1 Restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_2_Selbstbedienungsrestaurant {
            get {
                object obj = ResourceManager.GetObject("6.2 Selbstbedienungsrestaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_3_Kueche_zu_Restaurant {
            get {
                object obj = ResourceManager.GetObject("6.3 Kueche zu Restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_4_Kueche_zu_Selbstbedienungsrestaurant {
            get {
                object obj = ResourceManager.GetObject("6.4 Kueche zu Selbstbedienungsrestaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_1_Vorstellungsraum {
            get {
                object obj = ResourceManager.GetObject("7.1 Vorstellungsraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_2_Mehrzweckhalle {
            get {
                object obj = ResourceManager.GetObject("7.2 Mehrzweckhalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_3_Ausstellungshalle {
            get {
                object obj = ResourceManager.GetObject("7.3 Ausstellungshalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_1_Bettenzimmer {
            get {
                object obj = ResourceManager.GetObject("8.1 Bettenzimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_2_Stationszimmer {
            get {
                object obj = ResourceManager.GetObject("8.2 Stationszimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_3_Behandlungsraum {
            get {
                object obj = ResourceManager.GetObject("8.3 Behandlungsraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_1_Produktion__grobe_Arbeit_ {
            get {
                object obj = ResourceManager.GetObject("9.1 Produktion (grobe Arbeit)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_2_Produktion__feine_Arbeit_ {
            get {
                object obj = ResourceManager.GetObject("9.2 Produktion (feine Arbeit)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_3_Laborraum {
            get {
                object obj = ResourceManager.GetObject("9.3 Laborraum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC tech,electric efficiency,thermal efficiency,cost per m2,life cycle GHG factor kgCO2eq per m2
        ///GC_cheap,0.0,0.1,300.0,1.0
        ///GC_normal,0.0,0.2,400.0,2.0
        ///GC_high_tech,0.0,0.3,500.0,3.0.
        /// </summary>
        internal static string gc_efficiency {
            get {
                return ResourceManager.GetString("gc_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hive_Logo {
            get {
                object obj = ResourceManager.GetObject("Hive_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Building {
            get {
                object obj = ResourceManager.GetObject("IO_Building", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_CoreDistributor {
            get {
                object obj = ResourceManager.GetObject("IO_CoreDistributor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_CoreMerger {
            get {
                object obj = ResourceManager.GetObject("IO_CoreMerger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Energysytems {
            get {
                object obj = ResourceManager.GetObject("IO_Energysytems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Environment {
            get {
                object obj = ResourceManager.GetObject("IO_Environment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Para_Inputen {
            get {
                object obj = ResourceManager.GetObject("IO_Para_Inputen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Para_Inputenergyemitter {
            get {
                object obj = ResourceManager.GetObject("IO_Para_Inputenergyemitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Para_Inputenvpot {
            get {
                object obj = ResourceManager.GetObject("IO_Para_Inputenvpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Para_InputSIAroom {
            get {
                object obj = ResourceManager.GetObject("IO_Para_InputSIAroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Para_InputSolarTech {
            get {
                object obj = ResourceManager.GetObject("IO_Para_InputSolarTech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Results_Param {
            get {
                object obj = ResourceManager.GetObject("IO_Results_Param", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IO_Visualizer {
            get {
                object obj = ResourceManager.GetObject("IO_Visualizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Distconvtech {
            get {
                object obj = ResourceManager.GetObject("IOCore_Distconvtech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Distenergysystems {
            get {
                object obj = ResourceManager.GetObject("IOCore_Distenergysystems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Distenv {
            get {
                object obj = ResourceManager.GetObject("IOCore_Distenv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_DistSIAroom {
            get {
                object obj = ResourceManager.GetObject("IOCore_DistSIAroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_DistSolarsim {
            get {
                object obj = ResourceManager.GetObject("IOCore_DistSolarsim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Distsolartech {
            get {
                object obj = ResourceManager.GetObject("IOCore_Distsolartech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Merger_Gasboiler {
            get {
                object obj = ResourceManager.GetObject("IOCore_Merger_Gasboiler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Mergerchiller {
            get {
                object obj = ResourceManager.GetObject("IOCore_Mergerchiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Mergercombinedheatpower {
            get {
                object obj = ResourceManager.GetObject("IOCore_Mergercombinedheatpower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Mergercoolingexchanger {
            get {
                object obj = ResourceManager.GetObject("IOCore_Mergercoolingexchanger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Mergerelectricalstation {
            get {
                object obj = ResourceManager.GetObject("IOCore_Mergerelectricalstation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Mergerheatpump {
            get {
                object obj = ResourceManager.GetObject("IOCore_Mergerheatpump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IOCore_Mergersolartech {
            get {
                object obj = ResourceManager.GetObject("IOCore_Mergersolartech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV tech,electric efficiency,thermal efficiency,cost per m2,cost per kWp,life cycle GHG factor kgCO2eq per m2,life cycle GHG factor kgCO2eq per kWp,Lifetime
        ///polycristalline,0.206,0,633.656,3076,171.598,833,30
        ///monocristalline,0.228,0,701.328,3076,189.924,833,30
        ///CIGS,0.156,0,592.8,3800,121.68,780,30
        ///CdTe,0.182,0,691.6,3800,78.806,433,30
        ///HIT,0.209,0,642.884,3076,174.097,833,30
        ///.
        /// </summary>
        internal static string pv_efficiency {
            get {
                return ResourceManager.GetString("pv_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVT tech,electric efficiency,thermal efficiency,cost per m2,life cycle GHG factor kgCO2eq per m2
        ///PVT_cheap,NaN,NaN,NaN,NaN
        ///PVT_normal,NaN,NaN,NaN,NaN
        ///PVT_high_tech,NaN,NaN,NaN,NaN
        ///PVT,0.17,0.3,NaN,400
        ///.
        /// </summary>
        internal static string pvt_efficiency {
            get {
                return ResourceManager.GetString("pvt_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST tech;electric efficiency;thermal efficiency;cost per kWp;cost per m2;life cycle GHG factor kgCO2eq per kWp;life cycle GHG factor kgCO2eq per m2
        ///vacume_tube;0;0.45;4444.444444;2000;462.2222222;208
        ///flat_plate;0;0.45;4444.444444;2000;408.8888889;184
        ///.
        /// </summary>
        internal static string st_efficiency {
            get {
                return ResourceManager.GetString("st_efficiency", resourceCulture);
            }
        }
    }
}
