# coding=utf-8
"""
Implements predefined default values for SIA 380.1 calculations.

"""


def default_values(use_case, area, month):
    use_case_data = {
        "mfh": {'tau': 182.0,
                'theta_i': 26.0,
                'theta_e': 0,
                't': month,
                'A_op': 20.0,
                'A_w': 26.0,
                'U_op': 0.2,
                'U_w': 1.2,
                'Vdot_e': 1.0,
                'Vdot_inf': 0.15,
                'eta_rec': 0.75,
                'phi_P': 2.3,
                'phi_B': 2.7,
                'phi_G': 8.0,
                't_P': 4090.0,
                't_B': 1540.0,
                't_G': 1780.0,
                'g': 0.5,
                'f_sh': 84.0,
                'I': 0},
        "efh": {'tau': 164.0,
                'theta_i': 26.0,
                'theta_e': 0,
                't': month,
                'A_op': 20.0,
                'A_w': 38.0,
                'U_op': 0.2,
                'U_w': 1.2,
                'Vdot_e': 0.6,
                'Vdot_inf': 0.15,
                'eta_rec': 0.75,
                'phi_P': 1.4,
                'phi_B': 2.7,
                'phi_G': 8.0,
                't_P': 4090.0,
                't_B': 1450.0,
                't_G': 1780.0,
                'g': 0.5,
                'f_sh': 71.0,
                'I': 0},
        "office": {'tau': 117.0,
                   'theta_i': 26.0,
                   'theta_e': 0,
                   't': month,
                   'A_op': 36.0,
                   'A_w': 42.0,
                   'U_op': 0.2,
                   'U_w': 1.2,
                   'Vdot_e': 2.6,
                   'Vdot_inf': 0.15,
                   'eta_rec': 0.75,
                   'phi_P': 5.0,
                   'phi_B': 15.9,
                   'phi_G': 7.0,
                   't_P': 1500.0,
                   't_B': 1210.0,
                   't_G': 1930.0,
                   'g': 0.5,
                   'f_sh': 107.0,
                   'I': 0},
        "school": {'tau': 72.0,
                   'theta_i': 26.0,
                   'theta_e': 0,
                   't': month,
                   'A_op': 70.0,
                   'A_w': 95.0,
                   'U_op': 0.2,
                   'U_w': 1.2,
                   'Vdot_e': 8.3,
                   'Vdot_inf': 0.15,
                   'eta_rec': 0.75,
                   'phi_P': 23.3,
                   'phi_B': 14.0,
                   'phi_G': 4.0,
                   't_P': 1390.0,
                   't_B': 1180.0,
                   't_G': 1770.0,
                   'g': 0.5,
                   'f_sh': 245.0,
                   'I': 0}
    }

    tmp = use_case_data[use_case]

    return tmp['tau'], tmp['theta_i'], tmp['theta_e'], tmp['t'], tmp['A_op'], tmp['A_w'], tmp['U_op'], tmp['U_w'], tmp[
        'Vdot_e'] * area, tmp['Vdot_inf'] * area, tmp['eta_rec'], tmp['phi_P'] * area, tmp['phi_B'] * area, tmp[
               'phi_G'] * area, tmp['t_P'], tmp['t_B'], tmp['t_G'], tmp['g'], tmp['f_sh'] * area, tmp['I']
